openapi: "3.0.0"
info:
  version: 1.0.0
  title: "Transfer API"
  description: |-
    Esta é uma api de teste destinada ao desenvolvimento de um projeto de transferência de saldo entre contas.
    Alguns links para testes:
    - [Transferência de saldo](http://localhost:8000/api/transactions/create)
    - [Lista de clientes](http://localhost:8000/api/customers)
    - [Criação de cliente](http://localhost:8000/api/customers/create)
  license:
    name: MIT
  contact:
    name: Lucas Almeida
    email: lucas_brito@outlook.com
servers:
  - url: "http://localhost:8000/api"
    description: "Api de Dev"
tags:
  - name: customers
    description: "Responsável por `criar um cliente` e `listar clientes`"
  - name: transactions
    description: "Responsável por `efetuar uma transferência`"

paths:
  /customers/create:
      post:
        tags:
          - customers
        summary: Adiciona um novo cliente
        description: 'Responsável por adicionar um novo cliente,
        se o cliente já existir, retorna um erro.
        O cliente deve ser passado no corpo da requisição no formato JSON.
        O sistema diferencia os usuários pelo tipo podendo ser `common` ou `shopkeeper`.'
        requestBody:
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Customer'

        responses:
          '200':
            description: 'Cliente adicionado com sucesso'
            content:
              'application/json':
                schema:
                  type: object
                  properties:
                    status:
                      type: string
                      description: (error ou success)
                    code:
                      type: string
                      description: Código de error ou success
                    content:
                      $ref: '#/components/schemas/CustomerResponse'
          '422':
            description: 'Erro ao adicionar cliente'
            content:
              'application/json':
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      description: 'Mensagem de erro'
                    errors:
                      type: array
                      items:
                        type: string
                        description: 'Erros'
  /customers:
    get:
      tags:
        - customers
      summary: Busca os clientes
      description: 'Responsável por buscar todos os clientes cadastrados no sistema.'
      responses:
        '200':
          description: 'Cliente adicionado com sucesso'
          content:
            'application/json':
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: (error ou success)
                  code:
                    type: string
                    description: Código de error ou success
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/CustomerResponse'
  /transactions/create:
    post:
      tags:
        - transactions
      summary: Efetua uma transferncia
      description: 'Efetua uma transferncia'
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                source:
                  type: integer
                  description: 'Conta de origem'
                  example: 14419
                amount:
                  type: number
                  description: 'Valor da transferencia'
                  example: 100
                target:
                  type: integer
                  description: 'Conta de destino'
                  example: 14420
      responses:
        '200':
          description: successful operation
          content:
            'application/json':
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      message:
                        type: string
                        description: 'Transaction success'
                  status:
                    type: string
                    description: (error ou success)
                  code:
                    type: string
                    description: Código de error ou success
        '500':
          description: Bad request
          content:
            'application/json':
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: 'Transaction success'
                  status:
                    type: string
                    description: (error ou success)
                  code:
                    type: string
                    description: Código de error ou success

components:
  schemas:
    Customer:
      type: object
      properties:
        firstname:
          type: string
          description: Nome do cliente
          example: Example
          required: true
        lastname:
          type: string
          description: Sobrenome do cliente
          example: API
          required: true
        email:
          type: string
          description: Email do cliente
          example: example@example.com
          required: true
        document:
          type: string
          description: Documento do cliente (CPF ou CNPJ)
          example: '12345678901'
          required: true
        type:
          type: string
          description: Tipo do cliente (common ou shopkeeper)
          example: common
          required: true
        password:
          type: string
          description: Senha do cliente
          example: '98763541'
          required: true

    CustomerResponse:
      type: object
      properties:
        firstname:
          type: string
          description: Nome do cliente
          required: true
        lastname:
          type: string
          description: Sobrenome do cliente
          required: true
        email:
          type: string
          description: Email do cliente
          required: true
        document:
          type: string
          description: Documento do cliente (CPF ou CNPJ)
          required: true
        type:
          type: string
          description: Tipo do cliente (common ou shopkeeper)
          required: true
